#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Chris Townsend
#  Date: 2016-09-28
#
#  https://github.com/ctownsen357/Dockerfiles
#
#  License: see accompanying LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  www.linkedin.com/in/chris-r-townsend
#

language: python
python:
  - "2.7"

sudo: required

env:
  - DEBUG=1

notifications:
  email: false

branches:
  only:
    - master

install:
  - echo nothing to install

script:
  - make test
